/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CineApp;

import static CineApp.FilesFunction.ReadShow;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 * Ventana de modificacion de funciones
 *
 * @author Jose Vicente Vargas Mestanza
 */
public class PaginaModificaionFunctions extends javax.swing.JFrame {

    private ArrayList<String> nombres = new ArrayList();
    private ArrayList<String> carpetasCreadas = new ArrayList();
    private Functions funcion;
    private File ficheroOrigen;
    private File carpetaOrigen;

    /**
     * Constructor de la pagina de modificacion
     *
     * @author Jose Vicente Vargas Mestanza
     */
    public PaginaModificaionFunctions() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        File carpetas = new File(".\\Funciones");
        String[] cCreadas = carpetas.list();
        this.carpetasCreadas.add("Seleccione una opcion");
        this.carpetasCreadas.addAll(Arrays.asList(cCreadas));
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width / 2, height / 2);
        setLocationRelativeTo(null);
        initComponents();

        jlError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsfHora = new com.toedter.components.JSpinField();
        jsfMin = new com.toedter.components.JSpinField();
        jLabel1 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbSala = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        jlError = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtPelicula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsfHora.setEnabled(false);
        jsfHora.setMaximum(23);
        jsfHora.setMinimum(0);

        jsfMin.setEnabled(false);
        jsfMin.setMaximum(59);
        jsfMin.setMinimum(0);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(":");

        jbGuardar.setText("Modificacion");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Hora");

        jLabel3.setText("Visualizador y Modificador de Funciones");

        jdcFecha.setEnabled(false);

        jLabel4.setText("Fecha emision");

        jLabel5.setText("Pelicula");

        jcbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1", "Sala 2", "Sala 3", "Sala 4", "Sala 5", "Sala 6" }));
        jcbSala.setEnabled(false);

        jLabel6.setText("Sala");

        jLabel7.setText("Precio");

        tfPrecio.setEnabled(false);

        jlError.setForeground(new java.awt.Color(255, 0, 51));
        jlError.setText("jLabel8");

        jLabel8.setText("Fecha");

        jtPelicula.setEnabled(false);

        jLabel9.setText("Nombre y hora");

        jComboBox1.setModel(new DefaultComboBoxModel(carpetasCreadas.toArray()));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una fecha primero" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbVolver, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jsfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jsfMin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jcbSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(jtPelicula))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEliminar)
                                        .addGap(69, 69, 69)
                                        .addComponent(jbGuardar))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jsfMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jsfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbVolver)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Evento del boton de volver
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        this.setVisible(false);
        new PaginaPrincipal().setVisible(true);
    }//GEN-LAST:event_jbVolverActionPerformed
    /**
     * Evento del boton de guardar se encarga de validar y guardar las
     * modificaciones
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        Instant instant;
        ZonedDateTime zdt;
        LocalDate fecha = null;
        File file;

        boolean validacion = true;
        String error = "";
        Functions aux;
        Billboard cartelera = this.funcion.getBillboard();
        int hora = jsfHora.getValue();
        int min = jsfMin.getValue();
        int sala = jcbSala.getSelectedIndex();
        String precio = tfPrecio.getText();
        float precioNum = 0.0f;

        if (precio.isBlank()) {
            validacion = false;
            error += "No puede estar vacio el precio.\n";
        } else {
            try {
                precioNum = Float.parseFloat(precio);
            } catch (NumberFormatException nfe) {
                validacion = false;
                error += "Se ha introducio un valor no valido.\n";
            }
        }

        try {
            instant = jdcFecha.getDate().toInstant();
            zdt = instant.atZone(ZoneId.systemDefault());
            fecha = zdt.toLocalDate();
            if (fecha.isBefore(LocalDate.now())) {
                validacion = false;
                error += "No puede ser ninguna de las fechas menores que la actual.\n";
            } else if (fecha.isBefore(cartelera.getInicio()) || fecha.isAfter(cartelera.getFinalizacion())) {
                validacion = false;
                error += "La fecha debe ser entre " + cartelera.getInicio().toString() + " y " + cartelera.getFinalizacion().toString();
            }
        } catch (NullPointerException npe) {
            validacion = false;
            error += "No puede estar vacia la fecha.\n";
        }

        if (!validacion) {
            jlError.setText(error);
            jlError.setForeground(Color.red);
            jlError.setVisible(true);
        } else {
            aux = new Functions(cartelera, fecha, precioNum, sala, hora, min);
            file = FilesFunction.createFilesFunction(cartelera.getPelicula(), hora, min, fecha.toString());

            if (!file.exists() || file.equals(this.ficheroOrigen)) {
                this.ficheroOrigen.delete();
                jlError.setText("Se ha guardado correctamente");
                jlError.setVisible(true);
                jlError.setForeground(Color.blue);
                FilesFunction.WriteShow(file, aux);
                if (this.carpetaOrigen.list().length == 0) {
                    this.carpetaOrigen.delete();
                }
                vaciarDatos();
            } else {
                error = "Esta funcion ya existe";
                jlError.setText(error);
                jlError.setForeground(Color.red);
                jlError.setVisible(true);
            }
        }

    }//GEN-LAST:event_jbGuardarActionPerformed
    /**
     * Evento del combo box que se encarga de activar y asignar los elementos de
     * la segunda combo box
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        File file;
        if (jComboBox1.getSelectedIndex() == 0) {
            jComboBox2.setModel(new DefaultComboBoxModel());
            jComboBox2.setEnabled(false);
            jComboBox2.addItem("Seleccione una fecha primero");
            activarDesactivarDatos(false);
        } else {
            this.carpetaOrigen = new File(".\\Funciones\\" + jComboBox1.getSelectedItem());
            jComboBox2.setEnabled(true);
            jComboBox2.setModel(new DefaultComboBoxModel(this.carpetaOrigen.list()));
            this.ficheroOrigen = new File(".\\Funciones\\" + jComboBox1.getSelectedItem() + "\\" + jComboBox2.getSelectedItem());
            this.funcion = ReadShow(this.ficheroOrigen);
            ponerDatos();
            activarDesactivarDatos(true);
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed
    /**
     * Evento de la segunda combo box en el cual lee los ficheros de cada
     * funcion y los muestra
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        File file;
        if (jComboBox1.getSelectedIndex() != 0) {
            file = new File(".\\Funciones\\" + jComboBox1.getSelectedItem() + "\\" + jComboBox2.getSelectedItem());
            this.ficheroOrigen = file;
            this.funcion = ReadShow(file);
            ponerDatos();
            activarDesactivarDatos(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed
    /**
     * evento del boton de eliminar se encarga de eliminar la funcion
     * seleccionada
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.ficheroOrigen.delete();
        jlError.setText("Se ha eliminado correctamente");
        jlError.setVisible(true);
        jlError.setForeground(Color.blue);
        if (this.carpetaOrigen.list().length == 0) {
            this.carpetaOrigen.delete();
        }
        vaciarDatos();


    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Funcion encargada de poner los datos de las funciones
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void ponerDatos() {
        ZoneId defaultZoneId = ZoneId.systemDefault();
        if (this.funcion != null) {
            jsfHora.setValue(this.funcion.getHour());
            jsfMin.setValue(this.funcion.getMin());
            jcbSala.setSelectedIndex(this.funcion.getSala());
            jtPelicula.setText(this.funcion.getBillboard().getPelicula());
            tfPrecio.setText(String.valueOf(this.funcion.getPrecio()));
            jdcFecha.setDate(Date.from(this.funcion.getDate().atStartOfDay(defaultZoneId).toInstant()));
        }

    }

    /**
     * Funcion encargada de activar o desactivar los elementos de modificacion
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void activarDesactivarDatos(boolean activar) {
        jsfHora.setEnabled(activar);
        jbGuardar.setEnabled(activar);
        jsfHora.setEnabled(activar);
        jsfMin.setEnabled(activar);
        tfPrecio.setEnabled(activar);
        jcbSala.setEnabled(activar);
        jdcFecha.setEnabled(activar);
        btnEliminar.setEnabled(activar);
    }

    /**
     * Se encarga de vaciar los datos de los elementos de la ventana
     *
     * @author Jose Vicente Vargas Mestanza
     */
    private void vaciarDatos() {
        File carpetas = new File(".\\Funciones");
        String[] cCreadas = carpetas.list();
        this.carpetasCreadas = new ArrayList();

        jsfHora.setValue(0);
        jsfMin.setValue(0);
        jcbSala.setSelectedIndex(0);
        jtPelicula.setText("");
        tfPrecio.setText("");
        jdcFecha.setDate(null);
        jComboBox1.setSelectedIndex(0);
        activarDesactivarDatos(false);

        this.carpetasCreadas.add("Seleccione una opcion");
        this.carpetasCreadas.addAll(Arrays.asList(cCreadas));
        jComboBox1.setModel(new DefaultComboBoxModel(this.carpetasCreadas.toArray()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JComboBox<String> jcbSala;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel jlError;
    private com.toedter.components.JSpinField jsfHora;
    private com.toedter.components.JSpinField jsfMin;
    private javax.swing.JTextField jtPelicula;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
